### ISSUE TITLE
Not all tweets can be received

### ISSUE THREAD

**Issue by Examnes** [markowanga/stweet#100]
I know this is probably a common problem.　Below is a piece of code that has this problem.
`import stweet as st
import getproxy
import arrow
from stweet.twitter_api.twitter_auth_web_client_interceptor import TwitterAuthWebClientInterceptor
import copy
import random
from multiprocessing import Pool

def run_batched(request_task):
    search_tweets_task = copy.deepcopy(request_task)
    proxy = getproxy.get_proxy_sorted_by_speed(arrow.now().date().isoformat())[3][0]
    fastest_proxy = st.RequestsWebClientProxyConfig(f'socks5://{proxy}', f'socks5://{proxy}')
    web_client = st.RequestsWebClient(proxy=fastest_proxy,interceptors=[TwitterAuthWebClientInterceptor()])
    output_tweets = st.CollectorRawOutput()
    try:
        st.TweetSearchRunner(search_tweets_task=search_tweets_task,
                             tweet_raw_data_outputs=[output_tweets],
                             user_raw_data_outputs=[],
                             web_client=web_client).run()
    except Exception as e:
        print(e)
    output_tweets = output_tweets.get_raw_list()
    output_tweets = list(map(lambda x: x.to_json(), output_tweets))
    return output_tweets
    

def remove_duplicates(tweets):
    new_tweets = []
    # use id only
    ids = []
    for tweet in tweets:
        if tweet['id'] not in ids:
            ids.append(tweet['id'])
            new_tweets.append(tweet)
    return new_tweets

def try_search():
    since = arrow.get(2023, 1, 29, 0, 0, 0)
    until = arrow.get(2023, 1, 31, 0, 0, 0)
    request = st.SearchTweetsTask(all_words='kronii',since=since, until=until)

    # run 100 batches then merge
    with Pool(1000) as p:
        results = p.map(run_batched, [request]*1000)
    
    # merge results
    merged = []
    for result in results:
        merged.extend(result)

    # remove duplicates
    merged = remove_duplicates(merged)

    
        
    # print results
    
    with open('test.txt', 'w') as f:
        for tweet in merged:
            json = tweet
            f.write(f'[{json["id"]}] {json["full_text"]}\n')

    print(f'Found {len(merged)} tweets')

    

    

if __name__ == '__main__':
    try_search()
`
I chose a period of one day. The number of tweets I receive from each request varies. I do not quite understand why that is. So I just made a lot of requests to get all the tweets. Their overall number was more than in each individual response from the server. In other words, I can't be sure I got them all.Can I somehow influence the request to get all the tweets for a given period of time on request in a reasonable time?

**Comment by markowanga** [comment]
I have analyzed API, and I don't see a solution to that problem. API is limited. It's the same API like the twitter webpage as guest. There you can see similar behavior -- when you scroll page for pecific query the numer of tweetes can be various.
