### ISSUE TITLE
Using from_username and keywords search at the same time

### ISSUE THREAD

**Issue by HindyDS** [markowanga/stweet#46]
When I tried to search tweets with user name and keywords at the same time, it returns nothing.

**Comment by markowanga** [comment]
Please share me your code.
Here is my example which runs correct:
```python
import stweet as st

if __name__ == '__main__':
    task = st.SearchTweetsTask(all_words='president', from_username='JoeBiden')
    collector = st.CollectorTweetOutput()
    runner = st.TweetSearchRunner(task, tweet_outputs=[collector, st.PrintEveryNTweetOutput(100)])
    runner.run()
    print(len(collector.get_scrapped_tweets()))
```

**Comment by markowanga** [comment]
Did this example solve your problem?

**Comment by markowanga** [comment]
@HindyDS can I close this issue?

**Comment by HindyDS** [comment]
Actually, is that possible to scrap tweets from few different users at the
same time?

「Marcin Wątroba <notifications@github.com>」在 2021年2月20日 週六，下午5:33 寫道：

**Comment by markowanga** [comment]
You want to run two independent tasks in the same time?

**Comment by HindyDS** [comment]
> You want to run two independent tasks in the same time?

like instead of using 'JoeBiden', I hope I can scrap from JoeBiden and DonaldTrump at the same time by pass a list of strings, something like that.

import stweet as st

if __name__ == '__main__':
    task = st.SearchTweetsTask(all_words='president', from_username=['JoeBiden', 'DonaldTrump'])
    collector = st.CollectorTweetOutput()
    runner = st.TweetSearchRunner(task, tweet_outputs=[collector, st.PrintEveryNTweetOutput(100)])
    runner.run()
    print(len(collector.get_scrapped_tweets()))

**Comment by markowanga** [comment]
There are few options to define which tweets you need to scrap:
- If you want to scrap tweets with mentioned JoeBiden and DonaldTrump you need to use property `all_words` in `SearchTweetsTask` like `all_words='DonaldTrump JoeBiden'`
- If you want to scrap tweets with any mention of user you need to use property `any_word` in `SearchTweetsTask` like `any_word='DonaldTrump JoeBiden'`
- If you want to scrap users `from` two users you can scrap firstly from first user and secondly from second

Is it hopeful to your case?

**Comment by HindyDS** [comment]
I think the third option answered my question, thank you.
