### ISSUE TITLE
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by OmarMohammed88** [markowanga/stweet#62]
I got  this error while executing this code 
![image](https://user-images.githubusercontent.com/45721757/110505606-fb401580-8106-11eb-9498-a2650d2fdb20.png)

```
import stweet as st
start = timeit.default_timer()

task = st.SearchTweetsTask(
    language = st.Language.ARABIC,
    tweets_limit=2000000,
    all_words=''
)

tweets_collector = st.CollectorTweetOutput()
result = st.TweetSearchRunner(task, [tweets_collector]).run()
stop = timeit.default_timer()
print('Time: ', stop - start) 
```
any idea of the solution?

**Comment by chillerno1** [comment]
What happens if you try with a smaller tweet limit e.g. 1,000?

**Comment by OmarMohammed88** [comment]
yeah I tried that even with a limit of 100K tweets and it works but nothing more than that and I don't know why

**Comment by markowanga** [comment]
Error with large tweets scrapping is fixed in develop version (but then was 429 error code -- it looks that you have 104).
@OmarMohammed88  could you share me your Google Colab notebook (if you wan't to share it on GitHub you can send me e-mail).

**Comment by markowanga** [comment]
And how you run stweet on Google Colab when it runs notebooks with python 3.6 – stweet require python 3.7 or higher

**Comment by OmarMohammed88** [comment]
I sent the link of the notebook to you, and  the environment which I run on it is   Python 3.7.10

**Comment by markowanga** [comment]
@OmarMohammed88 thank you – I will check it 😉

**Comment by markowanga** [comment]
I'm preparing `stweet 2.0` right now. Twitter changed api on website, current API is deprecated. It can works with tor proxy.

**Comment by markowanga** [comment]
Hey, please use stweet 2.0 :D
