### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by HindyDS** [markowanga/stweet#67]
for i in range(1, 10):
        mine_tweets('#AMZN #amzn', f'201{i}-01-01', f'201{i}-06-01')
        
        mine_tweets('#AMZN #amzn', f'201{i}-06-01', f'201{i}-12-01')
        
    mine_tweets('#AMZN #amzn', '2021-01-01', '2021-06-01')  
    mine_tweets('#AMZN #amzn', '2021-06-01', '2021-12-01')

    ---------------------------------------------------------------------------
    PermissionError                           Traceback (most recent call last)
    <ipython-input-4-5d228fa6c5ce> in <module>
          1 for i in range(1, 10):
    ----> 2     mine_tweets('#AMZN #amzn', f'201{i}-01-01', f'201{i}-06-01')
          3 
          4     mine_tweets('#AMZN #amzn', f'201{i}-06-01', f'201{i}-12-01')
          5 
    
    <ipython-input-3-5dc95beed6ea> in mine_tweets(username, starting_date, finishing_date, no_days)
         17     run_result = st.TweetSearchRunner(
         18         search_tweets_task=task,
    ---> 19         tweet_outputs=tweet_outputs
         20     ).run()
    
    F:\Anaconda\lib\site-packages\stweet\search_runner\search_runner.py in run(self)
         50         self._prepare_token()
         51         while not self._is_end_of_scrapping():
    ---> 52             self._execute_next_tweets_request()
         53         return SearchTweetsResult(self.search_run_context.all_download_tweets_count)
         54 
    
    F:\Anaconda\lib\site-packages\stweet\search_runner\search_runner.py in _execute_next_tweets_request(self)
         68             parsed_tweets = self.tweet_parser.parse_tweets(response.text)
         69             self.search_run_context.scroll_token = self.tweet_parser.parse_cursor(response.text)
    ---> 70             self._process_new_scrapped_tweets(parsed_tweets)
         71         else:
         72             raise ScrapBatchBadResponse(response)
    
    F:\Anaconda\lib\site-packages\stweet\search_runner\search_runner.py in _process_new_scrapped_tweets(self, parsed_tweets)
         74 
         75     def _process_new_scrapped_tweets(self, parsed_tweets: List[Tweet]):
    ---> 76         self._process_new_tweets_to_output(parsed_tweets)
         77         self.search_run_context.last_tweets_download_count = len(parsed_tweets)
         78         self.search_run_context.add_downloaded_tweets_count(len(parsed_tweets))
    
    F:\Anaconda\lib\site-packages\stweet\search_runner\search_runner.py in _process_new_tweets_to_output(self, new_tweets)
         93     def _process_new_tweets_to_output(self, new_tweets: List[Tweet]):
         94         for tweet_output in self.tweet_outputs:
    ---> 95             tweet_output.export_tweets(new_tweets)
         96         return
    
    F:\Anaconda\lib\site-packages\stweet\tweet_output\csv_tweet_output.py in export_tweets(self, tweets)
         36             mode='a',
         37             header=self._header_to_add(),
    ---> 38             index=False
         39         )
         40         return
    
    ~\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py in to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, decimal, errors, storage_options)
       3400             doublequote=doublequote,
       3401             escapechar=escapechar,
    -> 3402             storage_options=storage_options,
       3403         )
       3404 
    
    ~\AppData\Roaming\Python\Python37\site-packages\pandas\io\formats\format.py in to_csv(self, path_or_buf, encoding, sep, columns, index_label, mode, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, errors, storage_options)
       1081             formatter=self.fmt,
       1082         )
    -> 1083         csv_formatter.save()
       1084 
       1085         if created_buffer:
    
    ~\AppData\Roaming\Python\Python37\site-packages\pandas\io\formats\csvs.py in save(self)
        232             errors=self.errors,
        233             compression=self.compression,
    --> 234             storage_options=self.storage_options,
        235         ) as handles:
        236 
    
    ~\AppData\Roaming\Python\Python37\site-packages\pandas\io\common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
        645                 encoding=ioargs.encoding,
        646                 errors=errors,
    --> 647                 newline="",
        648             )
        649         else:
    
    PermissionError: [Errno 13] Permission denied: '#AMZN #amzn_2014-01-01_to_2014-06-01.csv'

**Comment by markowanga** [comment]
Please add code of `mine_tweets`
