### ISSUE TITLE
stop after a while

### ISSUE THREAD

**Issue by jckling** [markowanga/stweet#71]
I want to crawl 2014-2021 tweets with `exact_words` (only one word), but it stopped and only picked up 2021.9.13 to 2021.9.4. Why does this happen?

**Comment by jckling** [comment]
It seems only get tweets within exactly one week 😢 

```python
    since = arrow.get('2014-01-01')
    search_tweets_task = st.SearchTweetsTask(
        exact_words=keywords[0],
        since=since,
        replies_filter=st.RepliesFilter.ONLY_ORIGINAL,
    )

    st.TweetSearchRunner(
        search_tweets_task=search_tweets_task,
        tweet_outputs=[st.CsvTweetOutput('2014-2021.csv'), st.PrintTweetOutput()],
        web_client=st.RequestsWebClient(proxy=proxies_config, verify=False),
    ).run()
```

add `until = arrow.get('2021-09-03')`, only get one day's tweets.

**Comment by markowanga** [comment]
Here is my code -- ot works and scrap tweets with no day limit
```
import arrow

import stweet as st

if __name__ == '__main__':
    since = arrow.get('2014-01-01')
    search_tweets_task = st.SearchTweetsTask(
        exact_words="#pis",
        since=since,
        replies_filter=st.RepliesFilter.ONLY_ORIGINAL,
    )
    st.TweetSearchRunner(
        search_tweets_task=search_tweets_task,
        tweet_outputs=[st.CsvTweetOutput('2014-2021.csv'), st.PrintTweetOutput()]
    ).run()
```
Which keyword are you looking for?

**Comment by jckling** [comment]
My keyword is `'medical assistance" OR "medical aid'`, search either of them.

**Comment by jckling** [comment]
Glad to see that!

**Comment by jckling** [comment]
This is the code, I'm using 2.0 with same proxy setting before, but throws `stweet.exceptions.scrap_batch_bad_response.ScrapBatchBadResponse: RequestResponse(status_code=403, text='')`

```python
import arrow
import stweet as st

ProxyConfig = st.RequestsWebClientProxyConfig(
    http_proxy="127.0.0.1:7890",
    https_proxy="127.0.0.1:7890"
)

if __name__ == '__main__':
    since = arrow.get('2021-10-01')
    until = arrow.get('2021-10-02')

    search_tweets_task = st.SearchTweetsTask(
        exact_words="nijisanji",
        since=since,
        until=until,
        replies_filter=st.RepliesFilter.ONLY_ORIGINAL,
    )

    st.TweetSearchRunner(
        search_tweets_task=search_tweets_task,
        tweet_raw_data_outputs=[st.JsonLineFileRawOutput('nijisanji_20211001_20211002.json'), st.PrintRawOutput()],
        user_raw_data_outputs=[st.PrintRawOutput()],
        web_client=st.RequestsWebClient(proxy=ProxyConfig),
    ).run()
```

BTW, how to set time interval? Does tweets data have user data, or split into `user_raw_data_outputs` ? 
Expecting more examples to show how  to use 😄

**Comment by markowanga** [comment]
If you are asking about users -- yes, searching tweets return users -- you can join it with tweets by ids 😉.
I'm returning RAW of responses, because it is hardly to parse, sometimes anu field isn't used etc. (I stweet 1.x I have many errors with parsing)

**Comment by markowanga** [comment]
About intervals – you set it correctly (`since` and `until`). Twitter give limitation for searching for not logged users. (try without -- you will receive max 200 tweets).
I'm using scrapping in very small intervals (`1 hour`, `10 minutes`):
```python
from arrow import Arrow

import stweet as st


class CovidScrapper:
    web_client: st.WebClient

    def __init__(self):
        self.web_client = st.DefaultTwitterWebClientProvider.get_web_client()

    def _scrap_for_hour(self, time_start: Arrow, json_lines_output: st.JsonLineFileRawOutput) -> int:
        print('scrap', time_start)
        collector = st.CollectorRawOutput()
        search_tweets_task = st.SearchTweetsTask(
            all_words="#covid19",
            since=time_start,
            until=time_start.shift(minutes=10),
            language=st.Language.POLISH
        )
        st.TweetSearchRunner(
            search_tweets_task=search_tweets_task,
            tweet_raw_data_outputs=[collector, json_lines_output],
            user_raw_data_outputs=[],
            web_client=self.web_client
        ).run()
        return len(collector.get_raw_list())

    def _scrap_for_day(self, time_midnight: Arrow) -> int:
        file_name = f'{time_midnight.date().isoformat()}.jsonl'
        json_lines_output = st.JsonLineFileRawOutput(f'tmp/data/{file_name}')
        return sum([
            self._scrap_for_hour(time_midnight.shift(minutes=it * 10), json_lines_output)
            for it in range(24 * 6)
        ])

    def run(self):
        init_time = Arrow(2020, 3, 1)
        for days_shift in range(500):
            shifted_time = init_time.shift(days=days_shift)
            print(shifted_time.isoformat(), self._scrap_for_day(shifted_time))


if __name__ == '__main__':
    CovidScrapper().run()
```

**Comment by soccerqi** [comment]
> Yes, I will prepare better docs in this month (now I focused on working library). Try add auth interceptor 😉 (yes it isn't obvious without documentation)
> 
> ```python
> st.RequestsWebClient(proxy=ProxyConfig, interceptors=[TwitterAuthWebClientInterceptor()])
> ```

How to use the TwitterAuthWebClientInterceptor?Thanks.

**Comment by markowanga** [comment]
You need to add it to `st.RequestsWebClient` ti Interceptor list. I don't know what exactly you need to explain. Please show some code it you want.

**Comment by soccerqi** [comment]
> 

Thanks！
When I use the code below:
st.RequestsWebClient(proxy=ProxyConfig, interceptors=[TwitterAuthWebClientInterceptor()])
My PyCharm prompts:Unresolved reference ‘TwitterAuthWebClientInterceptor’
so where is the TwitterAuthWebClientInterceptor?

**Comment by markowanga** [comment]
PyCharm should suggest what to import.
Please add:
```python
from stweet.twitter_api.twitter_auth_web_client_interceptor import TwitterAuthWebClientInterceptor
```

**Comment by soccerqi** [comment]
Many thanks！

发自我的iPhone
