### ISSUE TITLE
文字コードについて

### ISSUE THREAD

**Issue by Eartab1227** [markowanga/stweet#78]
こんにちは。
出力される文字コードについて質問があります。
公開されているサンプルコードをもとに実行したのですが、
ASCIIコードで出力されます。

unicodeで出力することは可能ですか？

**Comment by markowanga** [comment]
Hello,
Is it possible to write issue in English 😊?

**Comment by Eartab1227** [comment]
Hello,
I am a Japanese college student.

I have a question about character encoding

I tried to execute the code by referring to the published sample code.

However,
If you check the output,
It is output with an ASCII code such as "\ u6709 \ u6751 \".

I want it to be output in unicode,
Is it possible to set the encoding?

**Comment by markowanga** [comment]
I have two outputs in sample:
```python
output_json = st.JsonLineFileRawOutput('output_raw_id.jl')
output_print = st.PrintRawOutput()
```
If you have \ u6709 in JsonLine output it is normal -- please parse every line by `json.loads(line_value)`

**Comment by Eartab1227** [comment]
I solved my issue.

Thank you for kindly telling me

**Comment by markowanga** [comment]
Cool, if a new problem arises, I will try to help 😉
