### ISSUE TITLE
How to obtain HTTP status codes?

### ISSUE THREAD

**Issue by Mennaruuk** [markowanga/stweet#80]
Hello Marcin, I hope you are doing well.

As you may know, HTTP status checkers don’t do great on Twitter. Tweets that have been deleted or simply don’t exist can be shown as 200 despite them being 403 or 404.

I’m wondering: is there a way I can feed stweet a text file containing Tweet URLs and have stweet ask Twitter to tell me the status codes for these Tweets?

Thank you!

**Comment by markowanga** [comment]
Hello @Mennaruuk 😉,

Could You share me some example? I don't have Twitter API documentation 😞 and I will prepare all on my own by seeing different responses.

**Comment by Mennaruuk** [comment]
Absolutely!

Example of an active Tweet: https://twitter.com/EA/status/1488940167780048900
Example of a deleted Tweet: https://twitter.com/eascaaa/status/1230668542577692673
![gif](https://user-images.githubusercontent.com/52135169/152633259-4ebff067-a0d1-4e71-a5d3-2ff13bc4e151.gif)

**Comment by markowanga** [comment]
API doesn't return 403 or 404, let you check the inspector when you open https://twitter.com/eascaaa/status/1230668542577692673 url there are everywhere 200 response code.

I have error in this code:
```python
import stweet as st

ACTIVE = '1488940167780048900'
DELETED = '1230668542577692673'


def test_id(tweet_id: str):
    id_task = st.TweetsByIdTask(tweet_id)
    output_json = st.JsonLineFileRawOutput('output_raw_id.jl')
    output_print = st.PrintRawOutput()
    st.TweetsByIdRunner(tweets_by_id_task=id_task,
                        raw_data_outputs=[output_print, output_json]).run()


if __name__ == '__main__':
    test_id(ACTIVE)
    print('--------')
    test_id(DELETED)
```

Have you the same results?
I will consider how to fix it.

**Comment by Mennaruuk** [comment]
Sadly, I have the same results.

One trick I found was specifying a user agent of a crawling bot in the headers. A good one is DuckDuckGo's bot DuckDuckBot. (Others include BingBot, YandexBot, and Applebot.) Examples:

```
import requests, re

tweet_url ="https://twitter.com/EA/status/1488940167780048900 "
headers = {'user-agent':'Mozilla/5.0 (compatible; DuckDuckBot-Https/1.1; https://duckduckgo.com/duckduckbot)'}

response = requests.get(tweet_url, headers=headers, allow_redirects=False)
status_code = response.status_code
print(status_code)
------------------
200
```
```
import requests, re

tweet_url ="https://twitter.com/EA/status/1488940167780048900 "
headers = {'user-agent':'Mozilla/5.0 (compatible; DuckDuckBot-Https/1.1; https://duckduckgo.com/duckduckbot)'}

response = requests.get(tweet_url, headers=headers, allow_redirects=False)
status_code = response.status_code
print(status_code)
------------------
404
```
Of course, some users may not want to send their URLs over to Apple, Bing, DuckDuckGo, or Yandex, but stweet can tell them upfront that accurate status checking requires one of these bots, and DuckDuckGo is known for their privacy advocacy so I think that's a pragmatic solution.
