### ISSUE TITLE
What's the tweets returned by the TweetsByIdRunner.run()?

### ISSUE THREAD

**Issue by soccerqi** [markowanga/stweet#81]

**Comment by soccerqi** [comment]
For example, I used the TweetsByIdRunner function by a tweet id "1490645670004363265", but the stweet returned 2 tweets, I don't know why? 
so what's the tweets returned by the TweetsByIdRunner function?

**Comment by markowanga** [comment]
The API returns, two tweet, I didn't see original documentation of API

**Comment by SUIBE-jk** [comment]
> The API returns, two tweet, I didn't see original documentation of API
Version 2.0 has been updated with a lot of content, a little overwhelmed, now can still export directly to the csv format file?

**Comment by SUIBE-jk** [comment]
> The API returns, two tweet, I didn't see original documentation of API

Version 2.0 has been updated with a lot of content, a little overwhelmed, now can still export directly to the csv format file?
