### ISSUE TITLE
I can't get the tweet content

### ISSUE THREAD

**Issue by helloway123** [markowanga/stweet#85]
I want to get  tweet content from a twitter user named way42380182 used try_search() function,but resault is null. Than  used try_user_scrap() function,It was get the user's personal infomation not its tweet contents.
What should I do?
Thanks.

**Comment by markowanga** [comment]
Hi, please give me code to reproduce

**Comment by helloway123** [comment]
import stweet as st
import arrow


def try_search():
    search_tweets_task = st.SearchTweetsTask(
        # all_words='#covid19',
        from_username="way42380182"
        tweets_limit=10,
        # since = arrow.get('2021-10-01'),
        # until = arrow.get('2021-10-02')
    )
    output_jl_tweets = st.JsonLineFileRawOutput('output_raw_search_tweets.jl')
    output_jl_users = st.JsonLineFileRawOutput('output_raw_search_users.jl')
    output_print = st.PrintRawOutput()
    st.TweetSearchRunner(search_tweets_task=search_tweets_task,
                         tweet_raw_data_outputs=[output_print, output_jl_tweets],
                         user_raw_data_outputs=[output_print, output_jl_users]).run()


def try_user_scrap():
    # user_task = st.GetUsersTask(['iga_swiatek'])
    user_task = st.GetUsersTask(['way42380182'])
    output_json = st.JsonLineFileRawOutput('output_raw_user.jl')
    output_print = st.PrintRawOutput()
    st.GetUsersRunner(get_user_task=user_task, raw_data_outputs=[output_print, output_json]).run()


def try_tweet_by_id_scrap():
    id_task = st.TweetsByIdTask('1447348840164564994')
    output_json = st.JsonLineFileRawOutput('output_raw_id.jl')
    output_print = st.PrintRawOutput()
    st.TweetsByIdRunner(tweets_by_id_task=id_task,
                        raw_data_outputs=[output_print, output_json]).run()


if __name__ == '__main__':
    try_search()
    try_user_scrap()
    # try_tweet_by_id_scrap()

**Comment by helloway123** [comment]
`import stweet as st
import arrow


def try_search():
    search_tweets_task = st.SearchTweetsTask(
        # all_words='#covid19',
        from_username="way42380182"
        tweets_limit=10,
        # since = arrow.get('2021-10-01'),
        # until = arrow.get('2021-10-02')
    )
    output_jl_tweets = st.JsonLineFileRawOutput('output_raw_search_tweets.jl')
    output_jl_users = st.JsonLineFileRawOutput('output_raw_search_users.jl')
    output_print = st.PrintRawOutput()
    st.TweetSearchRunner(search_tweets_task=search_tweets_task,
                         tweet_raw_data_outputs=[output_print, output_jl_tweets],
                         user_raw_data_outputs=[output_print, output_jl_users]).run()


def try_user_scrap():
    # user_task = st.GetUsersTask(['iga_swiatek'])
    user_task = st.GetUsersTask(['way42380182'])
    output_json = st.JsonLineFileRawOutput('output_raw_user.jl')
    output_print = st.PrintRawOutput()
    st.GetUsersRunner(get_user_task=user_task, raw_data_outputs=[output_print, output_json]).run()


def try_tweet_by_id_scrap():
    id_task = st.TweetsByIdTask('1447348840164564994')
    output_json = st.JsonLineFileRawOutput('output_raw_id.jl')
    output_print = st.PrintRawOutput()
    st.TweetsByIdRunner(tweets_by_id_task=id_task,
                        raw_data_outputs=[output_print, output_json]).run()


if __name__ == '__main__':
    try_search()
    try_user_scrap()
    # try_tweet_by_id_scrap()`

**Comment by helloway123** [comment]
> Hi, please give me code to reproduce

Hi,have you seen my code? Haven't you found the problem yet?

**Comment by markowanga** [comment]
Hi, all results are saved in `.jl` files

**Comment by helloway123** [comment]
> Hi, all results are saved in `.jl` files

But there is no tweet text content about way42380182!!

**Comment by helloway123** [comment]
> Hi, all results are saved in `.jl` files

But there is really no tweet text content about way42380182!!

**Comment by helloway123** [comment]
> Hi, all results are saved in `.jl` files

Is it convenient to send your code and .jl files to my email 42380182@QQ.com.
Thanks!

**Comment by markowanga** [comment]
Hi, yes -- you are right, I will check this

**Comment by markowanga** [comment]
I think that there is bug on Twitter -- when I go to user profile i can find any tweets, but when want to find tweets by search (go to advanced and fill "from account") -- there are no result returned
