### ISSUE TITLE
AttributeError: module 'stweet' has no attribute 'GetUsersTask'

### ISSUE THREAD

**Issue by Keong96** [markowanga/stweet#88]
after i pip install -U stweet
i copy the example in readme, but it doesnt work
please help

**Comment by markowanga** [comment]
Have you tried in docker container?
What's your OS? Python version?

**Comment by Keong96** [comment]
no, I didn't try in docker container, i just try in command prompt
my os is win10

**Comment by markowanga** [comment]
Could you paste code and output (I know that it's in readme, but I want to have it here)

**Comment by lonngxiang** [comment]
> Could you paste code and output (I know that it's in readme, but I want to have it here)

![image](https://user-images.githubusercontent.com/40717349/209512569-ed823961-afc6-49be-ade5-d8842206c4a6.png)

**Comment by markowanga** [comment]
Please call:
```python
import stweet as st
print(dir(st))
```
And send me output

**Comment by markowanga** [comment]
And call in terminal
```bash
pip list
```
Check version of street

**Comment by markowanga** [comment]
#96
