### ISSUE TITLE
Filter Tweets by Source field

### ISSUE THREAD

**Issue by Lavriz** [markowanga/stweet#89]
Hey! Thank you **so much** for the Twint alternative :) 

I haven't found this info in the repo: is it possible to filter out tweets by source while searching?

Thanks in advance!

**Comment by Lavriz** [comment]
Also, could you please elaborate a little bit on why every search yields a different number of tweets? Is it all due to Twitter? Sorry for many questions!

**Comment by markowanga** [comment]
No, there is no option for this.
