### ISSUE TITLE
class SearchTweetsTask how to crawl more tweets

### ISSUE THREAD

**Issue by 1689665417** [markowanga/stweet#93]
code like this
search_tweets_task = st.SearchTweetsTask(from_username='AircraftSpots', tweets_limit=200)
but parameter 【tweets_limit】 It doesn't seem to work.
in fact, Run the code eatch time can get 25 tweets，how to get more tweets？

**Comment by 928095762** [comment]
I have the same question.

**Comment by markowanga** [comment]
See #92
