### ISSUE TITLE
AttributeError: module 'stweet' has no attribute 'JsonLineFileRawOutput'

### ISSUE THREAD

**Issue by lintangtimur** [markowanga/stweet#96]
when i run from example code in this repository i got following error
`AttributeError: module 'stweet' has no attribute 'JsonLineFileRawOutput`

OS: win11
Python 3.7

```python
import stweet as st
print(dir(st))
```

`
['CollectorTweetOutput', 'CollectorUserOutput', 'CsvTweetOutput', 'CsvUserOutput', 'GetUsersResult', 'GetUsersRunner', 'GetUsersTask', 'JsonLineFileTweetOutput', 'JsonLineFileUserOutput', 'Language', 'PrintEveryNTweetOutput', 'PrintEveryNUserOutput', 'PrintFirstInRequestTweetOutput', 'PrintTweetOutput', 'PrintUserOutput', 'RepliesFilter', 'RequestsWebClient', 'RequestsWebClientProxyConfig', 'SearchTweetsResult', 'SearchTweetsTask', 'Tweet', 'TweetOutput', 'TweetSearchRunner', 'TweetsByIdsResult', 'TweetsByIdsRunner', 'TweetsByIdsTask', 'User', 'UserOutput', 'WebClient', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'auth', 'exceptions', 'export_data', 'export_tweets_to_csv', 'export_tweets_to_json_lines', 'export_users_to_csv', 'export_users_to_json_lines', 'get_user_runner', 'http_request', 'import_data', 'mapper', 'model', 'read_tweets_from_csv_file', 'read_tweets_from_json_lines_file', 'read_users_from_csv_file', 'read_users_from_json_lines_file', 'search_runner', 'tweet_output', 'tweets_by_ids_runner', 'user_output']
`

any solution?

**Comment by markowanga** [comment]
Yes, please raise your python version to min 3.8 -- version 2.0 supports python above 3.8.
