### ISSUE TITLE
get all tweet 

### ISSUE THREAD

**Issue by lintangtimur** [markowanga/stweet#97]
Hi first of all sorry for my bad english and thank you for this repository.
I want to get all tweet from username to make chart in annual period. When i tested on my twitter account it is only get 70 tweets. Expected results should be 6.9k tweets

Below the code:
```python
search_tweets_task = st.SearchTweetsTask(from_username='stlintangtap')
    output_jl_tweets = st.JsonLineFileRawOutput('output_raw_search_tweets.jl')
    output_jl_users = st.JsonLineFileRawOutput('output_raw_search_users.jl')
    output_print = st.PrintRawOutput()
    st.TweetSearchRunner(search_tweets_task=search_tweets_task,
                         tweet_raw_data_outputs=[output_print, output_jl_tweets],
                         user_raw_data_outputs=[output_print, output_jl_users]).run()
```

**Comment by markowanga** [comment]
I have wrote in Readme – Twitter block to scrap large amount of tweets in one search.
Best way in your case is dividing search for periods -- in day unit.
